### ISSUE TITLE
Visualizing relative values of important features and risk

### ISSUE THREAD

**Issue by bpben** [insight-lane/crash-model#248]
As a city stakeholder, I want to understand a road segment's risk in context of a city's overall risk.  Additionally, I want to understand the segment's characteristics (e.g. speed limit) in context of the city's road network characteristics.

It seems like we could address this by contextualizing both the risk scores and some important segment features.  That means creating an output from the model that contains both the importance of different features and their city-wide average (see #103 ) and incorporating this into the visualization.

Thoughts, @alicefeng ?

**Comment by alicefeng** [comment]
Yeah this sounds about right to me.

In terms of contextualizing the risk scores, I think we could show the distribution of segments that fall into various risk bins (very low, low, medium, high, very high, etc) and then instead of the current slider, we can have some buttons that users click on to see a map of, for example, only segments with very high risk scores.

For the feature importances, I agree on showing the segment's specific values vs city averages/mode as a first stab at this.

**Comment by alicefeng** [comment]
Oh, one other tricky bit here is if we're planning on displaying features and their values, we're going to want to use human-readable ones.

**Comment by j-t-t** [comment]
We moved a little bit in this direction by adding human readable feature names as part of the config. We can store human readable feature values somewhere similar as well.

**Comment by bpben** [comment]
That makes sense, @alicefeng.  Maybe there's something in being able to click that low/medium/high selector and seeing how that changes the citywide averages on features.  Or something along those lines.  Sort of getting at the idea of "profiles", but without trying to pull out groupings analytically.

**Comment by bpben** [comment]
It seems like this is something we've incorporated to some extent in the showcase.  We can reopen when we have a new, clearer task around this.
